### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rodrigolitzius** [DeltaNedas/modding-toolbox#3]
Platform: Mobile
Build: 122.1
Issue: when going to the UI editor and exporting the UI, the game crashes.

Mindustry has crashed. How unfortunate.
Version: release build 122.1
OS: Linux x32
Java Version: 0
Java Architecture: null
10 Mods: dev-mode:2.3.2, modding-toolbox:3.7.1, ui-lib:2.16.4, unit-factory:2.4.2, waisa:2.3.3, anuke-logic:1.6.1, bugdustry:1, ldb:1.1.0, pictologic:1.5.2, rtfm:2.14.1

> EcmaError: 'TypeError: Cannot find function show in object [object Object]. (uieditor#36)'
ScriptRuntime.constructError: 3955
ScriptRuntime.constructError: 3935
ScriptRuntime.typeError: 3964
ScriptRuntime.typeError2: 3980
ScriptRuntime.notFunctionError: 4043
ScriptRuntime.getPropFunctionAndThisHelper: 2350
ScriptRuntime.getPropFunctionAndThis: 2333
OptRuntime.callProp0: 69
uieditor_12._c_anonymous_1: 36
uieditor_12.call: -1
ArrowFunction.call: 33
OptRuntime.callProp0: 71
uieditor_12._c_anonymous_19: 199
uieditor_12.call: -1
ContextFactory.doTopCall: 346
ScriptRuntime.doTopCall: 3303
uieditor_12.call: -1
ArrowFunction.call: 33
InterfaceAdapter.invokeImpl: 141
InterfaceAdapter.lambda$invoke$0$InterfaceAdapter: 92
-$$Lambda$InterfaceAdapter$GS5pe0iB_uMmYJOoJRJ6I3mO2jU.run: -1
Context.call: 524
ContextFactory.call: 446
InterfaceAdapter.invoke: 92
VMBridge_jdk18.lambda$newInterfaceProxy$0: 100
-$$Lambda$VMBridge_jdk18$ggYMF9TpGNVQ1Biw8Nj4QDudM_c.invoke: -1
Proxy.invoke: 813
$Proxy1.run: -1
Element.lambda$clicked$2: 893
-$$Lambda$Element$Z5rFlDuLK9b0NIGwxILHnJVs0B8.get: -1
Element$4.clicked: 902
ClickListener.touchUp: 77
InputListener.handle: 34
Scene.touchUp: 357
InputMultiplexer.touchUp: 137
AndroidInput.processEvents: 285
AndroidGraphics.onDrawFrame: 417
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

**Comment by deltanedas** [comment]
ok

**Comment by deltanedas** [comment]
ok
